.TH "yassi-script1" "1" "2015-08-10" "Simon Arjuna Erat (sea)"

.SH NAME
yassi-script1 (0.1)

.SH SYNOPSIS
\fByassi-script1\fP [options] [arguments]
.br
Example: yassi-script1
.br
Where options are:
.IP "\fB-XY\fP"
does this
.IP "\fB-YX\fP"
does that

.SH DESCRIPTION
.PP
Some descriptional text

.SH LICENSE

.br


.SH CONTACT
erat.simon@gmail.com
.br
linux-scripter.blogspot.com
